create table ipsums (
	id INT,
	blabla VARCHAR(50),
	lorem INT
);
insert into ipsums (id, blabla, lorem) values (1, 'regional', 2);
insert into ipsums (id, blabla, lorem) values (2, 'methodology', 3);
insert into ipsums (id, blabla, lorem) values (3, 'Profit-focused', 4);
insert into ipsums (id, blabla, lorem) values (4, 'didactic', 5);
insert into ipsums (id, blabla, lorem) values (5, 'foreground', 6);
insert into ipsums (id, blabla, lorem) values (6, 'hardware', 7);
insert into ipsums (id, blabla, lorem) values (7, 'Progressive', 8);
insert into ipsums (id, blabla, lorem) values (8, 'Ergonomic', 9);
insert into ipsums (id, blabla, lorem) values (9, 'bottom-line', 10);
insert into ipsums (id, blabla, lorem) values (10, 'zero tolerance', 11);
insert into ipsums (id, blabla, lorem) values (11, 'didactic', 12);
insert into ipsums (id, blabla, lorem) values (12, 'content-based', 13);
insert into ipsums (id, blabla, lorem) values (13, 'Organic', null);
insert into ipsums (id, blabla, lorem) values (14, 'capacity', 15);
insert into ipsums (id, blabla, lorem) values (15, 'reciprocal', 16);
insert into ipsums (id, blabla, lorem) values (16, 'static', 17);
insert into ipsums (id, blabla, lorem) values (17, 'secured line', 18);
insert into ipsums (id, blabla, lorem) values (18, 'heuristic', 19);
insert into ipsums (id, blabla, lorem) values (19, 'global', null);
insert into ipsums (id, blabla, lorem) values (20, 'scalable', 21);
insert into ipsums (id, blabla, lorem) values (21, 'Enterprise-wide', 22);
insert into ipsums (id, blabla, lorem) values (22, 'Multi-channelled', 23);
insert into ipsums (id, blabla, lorem) values (23, 'grid-enabled', 24);
insert into ipsums (id, blabla, lorem) values (24, 'background', 25);
insert into ipsums (id, blabla, lorem) values (25, 'hub', 26);
insert into ipsums (id, blabla, lorem) values (26, 'success', 27);
insert into ipsums (id, blabla, lorem) values (27, 'foreground', 28);
insert into ipsums (id, blabla, lorem) values (28, 'analyzer', 29);
insert into ipsums (id, blabla, lorem) values (29, 'attitude', 30);
insert into ipsums (id, blabla, lorem) values (30, 'mission-critical', 31);
insert into ipsums (id, blabla, lorem) values (31, 'Enhanced', 32);
insert into ipsums (id, blabla, lorem) values (32, 'functionalities', 33);
insert into ipsums (id, blabla, lorem) values (33, 'even-keeled', 34);
insert into ipsums (id, blabla, lorem) values (34, 'Visionary', 35);
insert into ipsums (id, blabla, lorem) values (35, 'Cross-platform', 36);
insert into ipsums (id, blabla, lorem) values (36, 'groupware', 37);
insert into ipsums (id, blabla, lorem) values (37, 'intermediate', 38);
insert into ipsums (id, blabla, lorem) values (38, 'Phased', 39);
insert into ipsums (id, blabla, lorem) values (39, 'discrete', 40);
insert into ipsums (id, blabla, lorem) values (40, 'Synergized', 41);
insert into ipsums (id, blabla, lorem) values (41, 'responsive', null);
insert into ipsums (id, blabla, lorem) values (42, 'Synchronised', 43);
insert into ipsums (id, blabla, lorem) values (43, 'Graphical User Interface', 44);
insert into ipsums (id, blabla, lorem) values (44, 'focus group', 45);
insert into ipsums (id, blabla, lorem) values (45, 'discrete', 46);
insert into ipsums (id, blabla, lorem) values (46, 'intangible', 47);
insert into ipsums (id, blabla, lorem) values (47, 'context-sensitive', 48);
insert into ipsums (id, blabla, lorem) values (48, 'zero defect', 49);
insert into ipsums (id, blabla, lorem) values (49, 'background', 50);
insert into ipsums (id, blabla, lorem) values (50, 'Organized', 51);
insert into ipsums (id, blabla, lorem) values (51, 'tangible', 52);
insert into ipsums (id, blabla, lorem) values (52, 'responsive', 53);
insert into ipsums (id, blabla, lorem) values (53, 'Exclusive', 54);
insert into ipsums (id, blabla, lorem) values (54, 'Horizontal', 55);
insert into ipsums (id, blabla, lorem) values (55, 'Quality-focused', 56);
insert into ipsums (id, blabla, lorem) values (56, 'explicit', 57);
insert into ipsums (id, blabla, lorem) values (57, 'Total', 58);
insert into ipsums (id, blabla, lorem) values (58, 'framework', 59);
insert into ipsums (id, blabla, lorem) values (59, 'asymmetric', 60);
insert into ipsums (id, blabla, lorem) values (60, 'system-worthy', 61);
insert into ipsums (id, blabla, lorem) values (61, 'contingency', 62);
insert into ipsums (id, blabla, lorem) values (62, 'User-centric', 63);
insert into ipsums (id, blabla, lorem) values (63, 'knowledge base', 64);
insert into ipsums (id, blabla, lorem) values (64, 'synergy', 65);
insert into ipsums (id, blabla, lorem) values (65, 'middleware', 66);
insert into ipsums (id, blabla, lorem) values (66, 'service-desk', 67);
insert into ipsums (id, blabla, lorem) values (67, 'complexity', 68);
insert into ipsums (id, blabla, lorem) values (68, 'optimizing', 69);
insert into ipsums (id, blabla, lorem) values (69, 'Fully-configurable', null);
insert into ipsums (id, blabla, lorem) values (70, 'attitude', 71);
insert into ipsums (id, blabla, lorem) values (71, 'pricing structure', 72);
insert into ipsums (id, blabla, lorem) values (72, 'parallelism', 73);
insert into ipsums (id, blabla, lorem) values (73, 'groupware', 74);
insert into ipsums (id, blabla, lorem) values (74, 'Decentralized', 75);
insert into ipsums (id, blabla, lorem) values (75, 'background', 76);
insert into ipsums (id, blabla, lorem) values (76, 'mobile', 77);
insert into ipsums (id, blabla, lorem) values (77, 'emulation', 78);
insert into ipsums (id, blabla, lorem) values (78, 'intermediate', 79);
insert into ipsums (id, blabla, lorem) values (79, 'open system', 80);
insert into ipsums (id, blabla, lorem) values (80, 'zero defect', 81);
insert into ipsums (id, blabla, lorem) values (81, 'matrix', 82);
insert into ipsums (id, blabla, lorem) values (82, 'ability', 83);
insert into ipsums (id, blabla, lorem) values (83, 'leverage', 84);
insert into ipsums (id, blabla, lorem) values (84, 'function', 85);
insert into ipsums (id, blabla, lorem) values (85, 'Phased', 86);
insert into ipsums (id, blabla, lorem) values (86, 'bandwidth-monitored', 87);
insert into ipsums (id, blabla, lorem) values (87, 'Object-based', 88);
insert into ipsums (id, blabla, lorem) values (88, 'capability', 89);
insert into ipsums (id, blabla, lorem) values (89, 'conglomeration', 90);
insert into ipsums (id, blabla, lorem) values (90, 'Visionary', 91);
insert into ipsums (id, blabla, lorem) values (91, 'clear-thinking', 92);
insert into ipsums (id, blabla, lorem) values (92, 'structure', 93);
insert into ipsums (id, blabla, lorem) values (93, 'projection', 94);
insert into ipsums (id, blabla, lorem) values (94, 'scalable', 95);
insert into ipsums (id, blabla, lorem) values (95, 'exuding', 96);
insert into ipsums (id, blabla, lorem) values (96, 'local', 97);
insert into ipsums (id, blabla, lorem) values (97, 'Progressive', 98);
insert into ipsums (id, blabla, lorem) values (98, 'utilisation', 99);
insert into ipsums (id, blabla, lorem) values (99, 'info-mediaries', null);
insert into ipsums (id, blabla, lorem) values (100, 'Extended', null);
