class ScoreBoard {
	constructor(){
		this.ones;
		this.twos;
		this.threes;
		this.fours;
		this.fives;
		this.sixes;
		this.sum;
		this.bonus;
		this.onePair;
		this.twoPairs;
		this.threeOfAKind;
		this.fourOfAKind;
		this.smallStraight;
		this.largeStraight;
		this.fullHouse;
		this.chance;
		this.yatzy;
	}
}